# Setup
title: D&D Tools
tagline: Resources for your 5e game
description: Tools, links, and APIs to help you run your 5e games.
permalink: pretty

github:
  repo: mloberg/dnd5e-api

version: 0.0.1

exclude:
  - "package*.json"
  - "*.config.js"
